description: Send updates on new released packs to slack channel
id: NewPacksNotifier
inputs: []
name: NewPacksNotifier
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0fcb6b5c-dde0-442e-83da-06180ef40bda
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 0fcb6b5c-dde0-442e-83da-06180ef40bda
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      bucket_name:
        simple: marketplace-dist
      object_name:
        simple: content/packs/index.zip
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieves object data into a file.
      id: 24dc713f-db4d-471d-8797-1d3683f7f5c8
      iscommand: true
      name: Download Index.zip from marketplace-dist
      script: '|||gcs-download-file'
      type: regular
      version: -1
    taskid: 24dc713f-db4d-471d-8797-1d3683f7f5c8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      entry_id:
        simple: ${File.EntryID}
      last_message_time_str:
        simple: ${LastRun}
      last_run_str:
        simple: ${LastRun}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Extract the index and gets a list of all new packs since last run
        into context.
      id: b02f3151-a6af-4d75-8a9d-56bbec35233f
      iscommand: false
      name: Build Slack Blocks From Index
      script: BuildSlackBlocksFromIndex
      type: regular
      version: -1
    taskid: b02f3151-a6af-4d75-8a9d-56bbec35233f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${Blocks}
          operator: isNotEqualString
          right:
            value:
              simple: no new packs
      label: "yes"
    id: "3"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if slack blocks is not "no new packs"
      id: 86ab52cf-8e14-47f6-890a-d628e634868f
      iscommand: false
      name: Check If Blocks Exists
      type: condition
      version: -1
    taskid: 86ab52cf-8e14-47f6-890a-d628e634868f
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      blocks:
        simple: ${Blocks}
      channel:
        simple: gfr-test
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends a message to a user, group, or channel.
      id: 8a620255-581d-4745-8b44-93f448cfc9ed
      iscommand: true
      name: Send Slack Message
      script: '|||send-notification'
      type: regular
      version: -1
    taskid: 8a620255-581d-4745-8b44-93f448cfc9ed
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 260,
          "y": 1420
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      listData:
        simple: ${LastRun.[1]}
      listName:
        simple: NewPacksNotifierLastRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.set
      id: 197e6715-6804-4f5e-88ba-382ed2d76910
      iscommand: true
      name: Set Last Run
      script: Builtin|||setList
      type: regular
      version: -1
    taskid: 197e6715-6804-4f5e-88ba-382ed2d76910
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      extend-context:
        simple: LastRun=.
      listName:
        simple: NewPacksNotifierLastRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.get
      id: 3c35c42b-f0de-4093-8e1a-994f775f317f
      iscommand: true
      name: Get Last Run
      script: Builtin|||getList
      type: regular
      version: -1
    taskid: 3c35c42b-f0de-4093-8e1a-994f775f317f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 05f5c564-ce2d-4da7-8aef-e23abcdea891
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 05f5c564-ce2d-4da7-8aef-e23abcdea891
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "9"
      "YES":
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      listName:
        simple: NewPacksNotifierLastRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if list exist in demisto lists.
      id: b8e4b0fa-42e3-4718-84cc-36ef9eba2f70
      iscommand: false
      name: Check If NewPacksNotifierLastRun List Exists
      script: IsListExist
      type: condition
      version: -1
    taskid: b8e4b0fa-42e3-4718-84cc-36ef9eba2f70
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      dateFormat:
        simple: iso
      daysAgo:
        simple: "7"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 238e4ff9-b087-4f92-85cd-e62dae08dc29
      iscommand: false
      name: Get Week Ago Time
      script: GetTime
      type: regular
      version: -1
    taskid: 238e4ff9-b087-4f92-85cd-e62dae08dc29
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 260,
          "y": 540
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      listData:
        simple: ${TimeNow}
      listName:
        simple: NewPacksNotifierLastRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.list.create
      id: 26efc848-d482-4d13-8d5b-5675a1cb00e0
      iscommand: true
      name: Create NewPacksNotifierLastRun List
      script: Builtin|||createList
      type: regular
      version: -1
    taskid: 26efc848-d482-4d13-8d5b-5675a1cb00e0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 260,
          "y": 710
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      closeReason:
        simple: Done
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 6a400b3b-00c6-4165-8c98-748d444ea7ef
      iscommand: true
      name: Close Incident
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 6a400b3b-00c6-4165-8c98-748d444ea7ef
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1960,
        "width": 590,
        "x": 50,
        "y": 50
      }
    }
  }
fromversion: 6.0.0
tests:
- No tests (auto formatted)
